services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: crh
      POSTGRES_USER: crh
      POSTGRES_PASSWORD: crh
    ports:
      - "5432:5432"
    volumes:
      - crh_pgdata:/var/lib/postgresql/data

  legacy:
    build: ./legacy-service
    environment:
      PORT: 8081
    ports:
      - "8082:8081"

  backend:
    build: ./backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/crh
      SPRING_DATASOURCE_USERNAME: crh
      SPRING_DATASOURCE_PASSWORD: crh
      CRH_JWT_SECRET: "change-me-in-real-life-change-me-in-real-life"
      CRH_LEGACY_BASE_URL: "http://legacy:8081"
      CRH_WEBHOOK_URL: "" # optionally set to a webhook URL
    depends_on:
      - db
      - legacy
    ports:
      - "8083:8080"   # changed to avoid "8080 already in use"

  frontend:
    build: ./frontend
    environment:
      VITE_API_BASE: "http://localhost:8083" # must match backend host port above
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  crh_pgdata:
